# Generated by Django 5.0.3 on 2024-04-12 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Books and Copy', 'Books and Copy'), ('Accessories', 'Accessories'), ('Electronics', 'Electronics'), ('Daily Essentials', 'Daily Essentials'), ('Stationary', 'Stationary'), ('Sports', 'Sports')], default='Daily Essentials', max_length=255),
            preserve_default=False,
        ),
    ]
