# Generated by Django 5.0.3 on 2024-04-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('books', 'Books and Copy'), ('accessories', 'Accessories'), ('electronics', 'Electronics'), ('essentials', 'Daily Essentials'), ('stationery', 'Stationery'), ('sports', 'Sports')], max_length=20),
        ),
    ]
